// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-M7V2keSg08OkjZTX61dsdCnYVXpTY',
    appId: '1:656478782739:web:YOUR_WEB_APP_ID',
    messagingSenderId: '656478782739',
    projectId: 'equal-push-notifications',
    authDomain: 'equal-push-notifications.firebaseapp.com',
    storageBucket: 'equal-push-notifications.firebasestorage.app',
    measurementId: 'G-YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-M7V2keSg08OkjZTX61dsdCnYVXpTY',
    appId: '1:656478782739:android:0f6462187949e2f58306e6',
    messagingSenderId: '656478782739',
    projectId: 'equal-push-notifications',
    storageBucket: 'equal-push-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-M7V2keSg08OkjZTX61dsdCnYVXpTY',
    appId: '1:656478782739:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '656478782739',
    projectId: 'equal-push-notifications',
    storageBucket: 'equal-push-notifications.firebasestorage.app',
    iosBundleId: 'com.equal.app.equal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-M7V2keSg08OkjZTX61dsdCnYVXpTY',
    appId: '1:656478782739:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '656478782739',
    projectId: 'equal-push-notifications',
    storageBucket: 'equal-push-notifications.firebasestorage.app',
    iosBundleId: 'com.equal.app.equal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-M7V2keSg08OkjZTX61dsdCnYVXpTY',
    appId: '1:656478782739:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '656478782739',
    projectId: 'equal-push-notifications',
    authDomain: 'equal-push-notifications.firebaseapp.com',
    storageBucket: 'equal-push-notifications.firebasestorage.app',
    measurementId: 'G-YOUR_MEASUREMENT_ID',
  );
}